django/interest/apps/int/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add$', views.add, name="add"),
    url(r'^users$', views.users, name="users"),
    url(r'^int/(?P<id>\d+)$', views.int, name="int")
]

django/interest/interest/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.int.urls', namespace="int")),
]

django/interest/apps/int/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    name=models.CharField(max_length=40)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)

class Interests(models.Model):
    interest=models.TextField(max_length=4000)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)

class UsersInterests(models.Model):
    user= models.ForeignKey(User, related_name="mainuser")
    interest= models.ForeignKey(Interests, related_name="maininterest")


# Create your models here.

django/interest/apps/int/views.py
from django.shortcuts import render, redirect
from .models import User, Interests, UsersInterests
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    return render(request, 'int/index.html')

def add(request):
    if request.method == "POST":
        if User.objects.filter(name=request.POST['name']):
            user = User.objects.get(name=request.POST['name'])
        else:
            user = User.objects.create(name = request.POST['name'])
        if Interests.objects.filter(interest=request.POST['interest']):
            interest = Interests.objects.get(interest=request.POST['interest'])
        else:
            interest = Interests.objects.create(interest = request.POST['interest'])
            print "here are the interests"
        UsersInterests.objects.create(user=user, interest=interest)
    return redirect(reverse('int:users'))


def users(request):
    context={
    'Users': User.objects.all()
    }
    print context['Users'][0]
    return render(request, 'int/show.html', context)

def int(request, id):
    context={
    'interests': UsersInterests.objects.filter(user__id=id)
    }
    return render(request, 'int/interest.html', context)

django/interest/apps/int/templates/int/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Interests</title>
  </head>
  <body>
    <form class="" action="{% url 'int:add'%}" method="post">
       {% csrf_token %} 
      Name: <input type="text" name="name" value="">
      <br>
      Interests:<input type="text" name="interest" value="">
      <br>
      <input type="submit" name="Submit!" value="Submit!">

    </form>

  </body>
</html>

django/interest/apps/int/templates/int/interest.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Interests</title>
  </head>
  <body>
    <h2>Hello, {{interests.first.user.name}} </h2>

    {%for item in interests%}


    {%endfor%}

    {%for item in interests%}
    <p>{{item.interest.interest}}</p>
    {%endfor%}
    <a href="{% url 'int:index'%}">enter another user interest</a>
    <a href="{% url 'int:users'%}">back to users</a>

  </body>
</html>

django/interest/apps/int/templates/int/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User info</title>
  </head>
  <body>
    <table>
      <tr>
        <td>User Name</td>
        <td>Action</td>
      </tr>
      {% for item in Users%}
      <tr>
        <td>{{item.name}}</td>
        <td><a href="{%url 'int:int' id=item.id%}">View</a></td>
      </tr>
        {%endfor%}
    </table>
  </body>
</html>